@startuml

class Storage{
    - data: Map<string, Object>
    + {abstract} save(data)
    + {abstract} load(): Object
}

class ModelDescriber{
    + {abstract} describe(inputs): string
}

class Generator{
    + {abstract} generate(inputs): string
}

class AIAssistant extends Generator{
    + {abstract} get_response(inputs): string
}



annotation CostAnalyzer extends AIAssistant{
    + get_response(inputs): string
}


class Node{
    - parents: List<INode>
    - was_executed: bool
    + {async} execute()
}

Node o--> Generator

class Graph{
    - endNode: INode
    + {async} execute()
}


Graph o-- Node


Node o-- Storage
Node o--> Node: "parents"

AIAssistant ..> InputType
AIAssistant ..> OutputType


CostAnalyzer .down.> AIAssistant
@enduml